name: Onboard to MemBrowse

on:
  workflow_dispatch:
    inputs:
      num_commits:
        description: 'Number of commits to process'
        required: true
        default: '10'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-matrix.outputs.targets }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Load target matrix
        id: set-matrix
        run: echo "targets=$(jq -c '.targets' .github/membrowse-targets.json)" >> $GITHUB_OUTPUT

  onboard:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.setup.outputs.targets) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: false

      - name: Update submodules
        run: |
          git submodule update --init --depth=1 --no-single-branch
          git -C lib/micropython/ submodule update --init --depth=1

      - name: Cache toolchains
        uses: actions/cache@v5
        id: cache
        with:
          path: |
            ~/cache/gcc
            ~/cache/llvm
            ~/cache/make
            ~/cache/stedgeai
          key: 'gcc-14.3.rel1_llvm-18.1.3_make-4.4.1_stedgeai-3.0'

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
          python-version: "3.12.4"

      - name: Install GNU Make
        if: steps.cache.outputs.cache-hit != 'true'
        run: source tools/ci.sh && ci_install_gnu_make

      - name: Install GCC toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        run: source tools/ci.sh && ci_install_arm_gcc

      - name: Install LLVM toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        run: source tools/ci.sh && ci_install_arm_llvm

      - name: Install STEdge AI tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: source tools/ci.sh && ci_install_stedgeai ${HOME}/cache/stedgeai

      - name: Install packages
        run: ${{ matrix.target.setup_cmd }}

      - name: Run MemBrowse Onboard Action
        uses: membrowse/membrowse-action/onboard-action@v1
        with:
          target_name: ${{ matrix.target.name }}
          num_commits: ${{ github.event.inputs.num_commits }}
          build_script: ${{ matrix.target.build_script }}
          elf: ${{ matrix.target.elf }}
          ld: ${{ matrix.target.ld }}
          linker_vars: ${{ matrix.target.linker_vars }}
          api_key: ${{ secrets.MEMBROWSE_API_KEY }}
